# Generated by Django 3.1.6 on 2021-03-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='course',
            name='video',
            field=models.FileField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='course',
            name='features',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
