# Generated by Django 3.1.6 on 2021-03-19 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210319_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='video',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
