# Generated by Django 3.1.6 on 2021-03-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210319_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='courseby',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
