# Generated by Django 3.1.6 on 2021-03-25 19:11

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210325_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courseby',
            field=models.CharField(blank=True, default=django.contrib.auth.models.User, max_length=200, null=True),
        ),
    ]
