# Generated by Django 3.1.6 on 2021-03-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210325_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courseby',
            field=models.CharField(default='hello', max_length=200),
        ),
    ]
